### ISSUE TITLE
allow restoring cluster after full k8s cluster deletion

### ISSUE THREAD

**Issue by pdeva** [FoundationDB/fdb-kubernetes-operator#1984] opened 2024-04-10 23:24 UTC
### What would you like to be added/changed?

reference this thread. https://forums.foundationdb.org/t/does-k8s-operator-allow-fully-resuming-after-terminating-and-recreating-all-fbd-pods/4158/7?u=pdeva

it seems currently if the k8s cluster dies for some reason or the other, the foundationdb cluster cannot be restored.

ideally the foundationdb cluster should be fully recoverable if k8s cluster can be recreated and my pv disks are still there.

**Comment by johscheuer** [comment] 2024-04-11 07:11
If the cluster is fully deleted, probably the links between the PVC's and the PV's is missing too, depending on what you define as "fully dies". In this case it sounds more like a problem that should be solved by another backup solution like https://velero.io for example.

Have you performed any tests to see if it's possible to restore a cluster? Having some steps to actually reproduce your request, including steps that you did to perform testing would be helpful. In general this rather sounds like an issue that should be solved by another backup solution specific for Kubernetes, like velero.io.

I'm also not sure if you comment in the forum post is correct:

> typically in a database, you only need the disks to be able to recover the database, eg kafka, postgres etc.

That probably depends a lot on the technology/operator that is used to provision and mange those databases. Without any mapping of the PVC <> PV, assuming that mapping is lost if the k8s cluster "dies", how should those databases recover?

**Comment by pdeva** [comment] 2024-04-11 11:00
hmm so lets say the k8s cluster itself remains. but if the fdb-operator itself needs to be deleted and recreated for some reason, will it restore itself fully?

**Comment by johscheuer** [comment] 2024-04-11 11:50
If you are talking about the deployment of the FDB Kubernetes operator, that shouldn't matter and the operator will start reconciling the cluster once the deployment is back. If you are talking about the CRD's, that will be an issue because the deletion of the CRD will also delete all resources created for it and you need a way to recreate those Kubernetes resources again, e.g. with velero.

As I mentioned in my earlier post, if you have any specific concerns how a deletion/recreation of the operator will be handled you should perform your own set of test for the scenarios that you have in mind. If you observe anything that doesn't behave like you would expect it feel free to create an issue with a set of steps on how to reproduce it and what you would expect.

**Comment by johscheuer** [comment] 2024-04-18 05:27
I'm going to close this issue. If you have any further questions feel free to ask them on the forum or here. If you discover any bugs or things that don't work as expected, feel free to open a new issue.

Thanks.

**Closed by johscheuer** 2024-04-18 05:27 UTC
Labels: question
