### ISSUE TITLE
Need to detect AttachVolume failures and handle in the operator.

### ISSUE THREAD

**Issue by jleach4** [FoundationDB/fdb-kubernetes-operator#972] opened 2021-11-01 23:02 UTC
```
Events:
  Type     Reason              Age                  From                     Message
  ----     ------              ----                 ----                     -------
  Warning  FailedScheduling    38m (x2 over 38m)    default-scheduler        0/330 nodes are available: 298 node(s) didn't match node selector, 32 Insufficient memory.
  Warning  FailedScheduling    37m                  default-scheduler        0/332 nodes are available: 300 node(s) didn't match node selector, 32 Insufficient memory.
  Normal   NotTriggerScaleUp   32m (x16 over 37m)   cluster-autoscaler       pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 node(s) didn't find available persistent volumes to bind, 1 node(s) didn't match node selector, 3 max node group size reached
  Normal   Scheduled           30m                  default-scheduler        Successfully assigned johnleachrq8ri4vl8gwd1ddroagqdv5y/fdb-cluster-jbfgfah6-4zds-primary-log-8 to ip-100-82-105-61.us-west-2.compute.internal
  Warning  FailedAttachVolume  30m                  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-a51ed71b-75e1-4280-b98a-437ef1ad4e31" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  FailedMount         12m (x2 over 19m)    kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[fdb-certs data fdb-trace-logs config-map dynamic-conf default-token-crl2w]: timed out waiting for the condition
  Warning  FailedMount         10m (x3 over 23m)    kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[dynamic-conf default-token-crl2w fdb-certs data fdb-trace-logs config-map]: timed out waiting for the condition
  Warning  FailedMount         7m48s (x2 over 21m)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[fdb-trace-logs config-map dynamic-conf default-token-crl2w fdb-certs data]: timed out waiting for the condition
  Warning  FailedMount         5m33s (x3 over 28m)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[default-token-crl2w fdb-certs data fdb-trace-logs config-map dynamic-conf]: timed out waiting for the condition
  Warning  FailedMount         3m16s (x2 over 25m)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data fdb-trace-logs config-map dynamic-conf default-token-crl2w fdb-certs]: timed out waiting for the condition
  Warning  FailedAttachVolume  86s (x21 over 30m)   attachdetach-controller  AttachVolume.Attach failed for volume "pvc-a51ed71b-75e1-4280-b98a-437ef1ad4e31" : rpc error: code = Internal desc = Could not attach volume "vol-0bae6c4503cd76e11" to node "i-0e889c2277b0ad8b8": attachment of disk "vol-0bae6c4503cd76e11" failed, expected device to be attached but was attaching
  Warning  FailedMount         60s                  kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[config-map dynamic-conf default-token-crl2w fdb-certs data fdb-trace-logs]: timed out waiting for the condition
```

**Comment by jleach4** [comment] 2021-11-01 23:03
I see this sporadically, especially with large clusters.  It significantly delays the cluster coming up for testing and perf testing.

**Comment by johscheuer** [comment] 2021-11-02 08:26
I don't think that the operator can do anything here. The issue is that the EBS volume is not already attached, depending on the EKS cluster and the load it can take some time. IMHO that must be solved by the cluster and not the operator. The only thing that the operator can do (and will do) is replacing the Pod (default wait time is 30min).

**Comment by jleach4** [comment] 2021-11-02 17:41
@johscheuer I expect K8s to have pods that hang for a multitude of reasons.  I would also expect an operator as it matures to handle such cases to facilitate healthy FDB clusters.

**Comment by brownleej** [comment] 2021-11-03 21:15
It should be able to handle those cases by replacing the pods. We can talk about more nuanced checks based on specific events, and simpler remediations like deleting pods rather than replacing them with new process groups, but I would see that more as an optimization.

**Comment by johscheuer** [comment] 2021-11-11 08:31
Out of curiosity what version of the operator are you using? I assume a version below `0.46.0` upgrading the operator to this version should fix that problem. That version added support to replace Pods without an address (unscheduled): https://github.com/FoundationDB/fdb-kubernetes-operator/releases/tag/v0.46.0 you also might want to reduce the `failureDetectionTimeSeconds` to something smaller than the default of `1800s`.

I'm closing this issue since the operator should handle that case already. If there are any other issues feel free to reopen it.

**Closed by johscheuer** 2021-11-11 08:31 UTC
