### ISSUE TITLE
Shorthand for copying all binaries in the sidecar

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#724] opened 2021-06-01 18:14 UTC
We've reworked our sample configuration for the operator to use the sidecar image in init mode to provide the operator with binaries for multiple FDB versions. This currently requires specifying a list of binaries to copy over. I think it would be useful to have a shorthand for copying all known binaries. This would reduce the chance of someone accidentally leaving out the binaries when setting up their deployment.

**Comment by johscheuer** [comment] 2021-06-21 09:28
Duplicate of https://github.com/FoundationDB/fdb-kubernetes-operator/issues/600?

**Comment by brownleej** [comment] 2021-06-22 17:12
It's not a full duplicate, but we might want to merge them into one issue. This discusses copying the binaries, such as `fdbcli` and `fdbbackup`.

**Closed** 2024-03-04 17:25 UTC
Labels: enhancement
