### ISSUE TITLE
Adding separate conditions for incorrect specs and incorrect metadata

### ISSUE THREAD

**Issue by brownleej** [FoundationDB/fdb-kubernetes-operator#955] opened 2021-10-22 01:49 UTC
We currently use the IncorrectPodSpec to reference a pod having an incorrect spec or incorrect metadata. This can lead to confusion about what the problem is, given that the name is specific about it being the spec, and the steps for updating the spec and the metadata are separate. I think it would be cleaner to have separate conditions for these things.

**Comment by johscheuer** [comment] 2021-11-16 21:07
Duplicate of https://github.com/FoundationDB/fdb-kubernetes-operator/issues/611

**Closed by johscheuer** 2021-11-16 21:07 UTC
Labels: technical-debt
